title: Veil & Vine Cleaning Co.
tagline: Care you can feel. Clean you can trust.
description: Tended spaces. Trusted hands. We bring intention and integrity to your home or office space.
baseurl: ""
url: "https://www.veilvinecleaning.com"
theme: minima

author:
  name: Veil & Vine Cleaning
  email: contact@veilvinecleaning.com

  Add site configuration
